### ISSUE TITLE
Template in readme.md does not work / missing wrong parameters

### ISSUE THREAD

**Issue by eddriesen** [myTselection/telenet_telemeter#14]
Hi, I have a "wigo" shake thingy, with the gigabit speedboost. includedvolume_usage and extendedvolume_usage are null; and when I use the example template, the top stack stays empty because of the null values (obviously).

So TL:DR;
extendedvolume_usage & includedvolume_usage are null.
no indication of Gbit connection (dlspeed is stated 300 instead of 1000)

attribution: Telenet Telemeter
last update: '2023-01-28T11:21:10.0+01:00'
used_percentage: 46.67
included_volume: 786432000
extended_volume: 0
total_volume: 750
wifree_usage: 0
includedvolume_usage: null
extendedvolume_usage: null
peak_usage: 367055704
offpeak_usage: 318939460
period_start: '2023-01-06T00:00:00+01:00'
period_end: '2023-02-05T00:00:00+01:00'
period_days_left: 9
period_used_percentage: 70
product: WIGOINT35
download_speed: 300 Mbps
upload_speed: 20 Mbps
telemeter_json:
 <SNIP!>

**Comment by myTselection** [comment]
dear eddriesen, if you could share your telemeter_json, I'm willing to take a look what would go wrong. I have the *_usage elements with data indicating overall usage.

**Comment by eddriesen** [comment]
> dear eddriesen, if you could share your telemeter_json, I'm willing to take a look what would go wrong. I have the *_usage elements with data indicating overall usage. May also be related to some ongoing changes in the backend of Telenet these days: https://community.home-assistant.io/t/telenet-telemeter-isp-monthly-data-usage/444810/15?u=myt

How do I extract the json data?

**Comment by myTselection** [comment]
> How do I extract the json data?

it's the attribute you snipped out of your first message. You can remove personal data  but please share everything else;

**Comment by eddriesen** [comment]
Sorry; hectic week ;) 
Here's the requested output;


```
attribution: Telenet Telemeter
last update: '2023-02-11T18:00:33.9+01:00'
used_percentage: 21.53
included_volume: 786432000
extended_volume: 0
total_volume: 750
wifree_usage: 0
includedvolume_usage: null
extendedvolume_usage: null
peak_usage: 169315783
offpeak_usage: 82334618
period_start: '2023-02-06T00:00:00+01:00'
period_end: '2023-03-05T00:00:00+01:00'
period_days_left: 23
period_used_percentage: 14.81
product: WIGOINT35
download_speed: 300 Mbps
upload_speed: 20 Mbps
telemeter_json:
  internetusage:
    - businessidentifier: xxxxxxxxx
      lastupdated: '2023-02-11T18:00:33.9+01:00'
      address:
        street: xxxxxxxxxxxxxxx
        postalcode: 'xxxx'
        municipality: xxxxxxxxx
        country: België
        housenr: 'xx'
        addressid: xxxxxxxxxxxxxxx
      availableperiods:
        - start: '2023-02-06T00:00:00.0+01:00'
          end: '2023-03-05T00:00:00.0+01:00'
          usages:
            - producttype: WIGOINT35
              specurl: https://api.prd.telenet.be/omapi/public/product/627
              squeezed: false
              periodstart: '2023-02-06T00:00:00.0+01:00'
              periodend: '2023-03-05T00:00:00.0+01:00'
              includedvolume: 10485759988465664
              extendedvolume:
                volume: 0
                cost: 0
                currency: EUR
              totalusage:
                wifree: 0
                dailyusages:
                  - date: '2023-02-06T00:00:00.0+01:00'
                    wifree: 0
                    peak: 15632587
                    offpeak: 17557453
                  - date: '2023-02-07T00:00:00.0+01:00'
                    wifree: 0
                    peak: 17800383
                    offpeak: 7403652
                  - date: '2023-02-08T00:00:00.0+01:00'
                    wifree: 0
                    peak: 21384516
                    offpeak: 11363062
                  - date: '2023-02-09T00:00:00.0+01:00'
                    wifree: 0
                    peak: 16048594
                    offpeak: 16746204
                  - date: '2023-02-10T00:00:00.0+01:00'
                    wifree: 0
                    peak: 13376733
                    offpeak: 4143648
                  - date: '2023-02-11T00:00:00.0+01:00'
                    wifree: 0
                    peak: 85072970
                    offpeak: 25120599
                peak: 169315783
                offpeak: 82334618
        - start: '2023-01-06T00:00:00.0+01:00'
          end: '2023-02-05T00:00:00.0+01:00'
          usages:
            - producttype: WIGOINT35
              specurl: https://api.prd.telenet.be/omapi/public/product/627
              squeezed: false
              periodstart: '2023-01-06T00:00:00.0+01:00'
              periodend: '2023-02-05T00:00:00.0+01:00'
              includedvolume: 10485759988465664
              extendedvolume:
                volume: 0
                cost: 0
                currency: EUR
              totalusage:
                wifree: 0
                dailyusages:
                  - date: '2023-01-06T00:00:00.0+01:00'
                    wifree: 0
                    peak: 18043248
                    offpeak: 24636255
                  - date: '2023-01-07T00:00:00.0+01:00'
                    wifree: 0
                    peak: 16093624
                    offpeak: 17314226
                  - date: '2023-01-08T00:00:00.0+01:00'
                    wifree: 0
                    peak: 19393034
                    offpeak: 18635015
                  - date: '2023-01-09T00:00:00.0+01:00'
                    wifree: 0
                    peak: 15119438
                    offpeak: 8904473
                  - date: '2023-01-10T00:00:00.0+01:00'
                    wifree: 0
                    peak: 10116285
                    offpeak: 6618326
                  - date: '2023-01-11T00:00:00.0+01:00'
                    wifree: 0
                    peak: 22072640
                    offpeak: 10703476
                  - date: '2023-01-12T00:00:00.0+01:00'
                    wifree: 0
                    peak: 10536221
                    offpeak: 7752628
                  - date: '2023-01-13T00:00:00.0+01:00'
                    wifree: 0
                    peak: 13770684
                    offpeak: 7100967
                  - date: '2023-01-14T00:00:00.0+01:00'
                    wifree: 0
                    peak: 16733237
                    offpeak: 18408120
                  - date: '2023-01-15T00:00:00.0+01:00'
                    wifree: 0
                    peak: 16068162
                    offpeak: 16609346
                  - date: '2023-01-16T00:00:00.0+01:00'
                    wifree: 0
                    peak: 16545808
                    offpeak: 4246973
                  - date: '2023-01-17T00:00:00.0+01:00'
                    wifree: 0
                    peak: 22378125
                    offpeak: 6848074
                  - date: '2023-01-18T00:00:00.0+01:00'
                    wifree: 0
                    peak: 25357264
                    offpeak: 6305993
                  - date: '2023-01-19T00:00:00.0+01:00'
                    wifree: 0
                    peak: 8306367
                    offpeak: 7593231
                  - date: '2023-01-20T00:00:00.0+01:00'
                    wifree: 0
                    peak: 32810374
                    offpeak: 11134714
                  - date: '2023-01-21T00:00:00.0+01:00'
                    wifree: 0
                    peak: 9257573
                    offpeak: 21590802
                  - date: '2023-01-22T00:00:00.0+01:00'
                    wifree: 0
                    peak: 22781971
                    offpeak: 69689406
                  - date: '2023-01-23T00:00:00.0+01:00'
                    wifree: 0
                    peak: 15871617
                    offpeak: 9244445
                  - date: '2023-01-24T00:00:00.0+01:00'
                    wifree: 0
                    peak: 12514771
                    offpeak: 14340072
                  - date: '2023-01-25T00:00:00.0+01:00'
                    wifree: 0
                    peak: 18357247
                    offpeak: 9151006
                  - date: '2023-01-26T00:00:00.0+01:00'
                    wifree: 0
                    peak: 14350823
                    offpeak: 5434229
                  - date: '2023-01-27T00:00:00.0+01:00'
                    wifree: 0
                    peak: 10577191
                    offpeak: 5048530
                  - date: '2023-01-28T00:00:00.0+01:00'
                    wifree: 0
                    peak: 6504459
                    offpeak: 22804968
                  - date: '2023-01-29T00:00:00.0+01:00'
                    wifree: 0
                    peak: 10786114
                    offpeak: 0
                  - date: '2023-01-30T00:00:00.0+01:00'
                    wifree: 0
                    peak: 116236855
                    offpeak: 38193352
                  - date: '2023-01-31T00:00:00.0+01:00'
                    wifree: 0
                    peak: 10463243
                    offpeak: 41690001
                  - date: '2023-02-01T00:00:00.0+01:00'
                    wifree: 0
                    peak: 13706238
                    offpeak: 30181636
                  - date: '2023-02-02T00:00:00.0+01:00'
                    wifree: 0
                    peak: 29926438
                    offpeak: 8654174
                  - date: '2023-02-03T00:00:00.0+01:00'
                    wifree: 0
                    peak: 28743020
                    offpeak: 11327809
                  - date: '2023-02-04T00:00:00.0+01:00'
                    wifree: 0
                    peak: 32597815
                    offpeak: 18420883
                  - date: '2023-02-05T00:00:00.0+01:00'
                    wifree: 0
                    peak: 10603149
                    offpeak: 14037776
                peak: 626623035
                offpeak: 492620906
        - start: '2022-12-06T00:00:00.0+01:00'
          end: '2023-01-05T00:00:00.0+01:00'
          usages:
            - producttype: WIGOINT35
              specurl: https://api.prd.telenet.be/omapi/public/product/627
              squeezed: false
              periodstart: '2022-12-06T00:00:00.0+01:00'
              periodend: '2023-01-05T00:00:00.0+01:00'
              includedvolume: 10485759988465664
              extendedvolume:
                volume: 0
                cost: 0
                currency: EUR
              totalusage:
                wifree: 0
                dailyusages:
                  - date: '2022-12-06T00:00:00.0+01:00'
                    wifree: 0
                    peak: 11339303
                    offpeak: 28615501
                  - date: '2022-12-07T00:00:00.0+01:00'
                    wifree: 0
                    peak: 9631817
                    offpeak: 23364500
                  - date: '2022-12-08T00:00:00.0+01:00'
                    wifree: 0
                    peak: 11660988
                    offpeak: 29753664
                  - date: '2022-12-09T00:00:00.0+01:00'
                    wifree: 0
                    peak: 7775516
                    offpeak: 69082489
                  - date: '2022-12-10T00:00:00.0+01:00'
                    wifree: 0
                    peak: 70991096
                    offpeak: 32685213
                  - date: '2022-12-11T00:00:00.0+01:00'
                    wifree: 0
                    peak: 13449046
                    offpeak: 32734052
                  - date: '2022-12-12T00:00:00.0+01:00'
                    wifree: 0
                    peak: 30123859
                    offpeak: 30732294
                  - date: '2022-12-13T00:00:00.0+01:00'
                    wifree: 0
                    peak: 26966239
                    offpeak: 25334729
                  - date: '2022-12-14T00:00:00.0+01:00'
                    wifree: 0
                    peak: 17378769
                    offpeak: 15291337
                  - date: '2022-12-15T00:00:00.0+01:00'
                    wifree: 0
                    peak: 61215680
                    offpeak: 21192961
                  - date: '2022-12-16T00:00:00.0+01:00'
                    wifree: 0
                    peak: 17299928
                    offpeak: 23256889
                  - date: '2022-12-17T00:00:00.0+01:00'
                    wifree: 0
                    peak: 7179288
                    offpeak: 15153900
                  - date: '2022-12-18T00:00:00.0+01:00'
                    wifree: 0
                    peak: 23905204
                    offpeak: 18617810
                  - date: '2022-12-19T00:00:00.0+01:00'
                    wifree: 0
                    peak: 13707440
                    offpeak: 63134204
                  - date: '2022-12-20T00:00:00.0+01:00'
                    wifree: 0
                    peak: 11225429
                    offpeak: 6386757
                  - date: '2022-12-21T00:00:00.0+01:00'
                    wifree: 0
                    peak: 15248861
                    offpeak: 12181894
                  - date: '2022-12-22T00:00:00.0+01:00'
                    wifree: 0
                    peak: 15172009
                    offpeak: 18207285
                  - date: '2022-12-23T00:00:00.0+01:00'
                    wifree: 0
                    peak: 14168638
                    offpeak: 10047742
                  - date: '2022-12-24T00:00:00.0+01:00'
                    wifree: 0
                    peak: 16763457
                    offpeak: 42797169
                  - date: '2022-12-25T00:00:00.0+01:00'
                    wifree: 0
                    peak: 21237986
                    offpeak: 16112180
                  - date: '2022-12-26T00:00:00.0+01:00'
                    wifree: 0
                    peak: 19206195
                    offpeak: 24918685
                  - date: '2022-12-27T00:00:00.0+01:00'
                    wifree: 0
                    peak: 12986029
                    offpeak: 8254957
                  - date: '2022-12-28T00:00:00.0+01:00'
                    wifree: 0
                    peak: 40846822
                    offpeak: 7777342
                  - date: '2022-12-29T00:00:00.0+01:00'
                    wifree: 0
                    peak: 86043133
                    offpeak: 33515160
                  - date: '2022-12-30T00:00:00.0+01:00'
                    wifree: 0
                    peak: 17504897
                    offpeak: 12058471
                  - date: '2022-12-31T00:00:00.0+01:00'
                    wifree: 0
                    peak: 8822435
                    offpeak: 15791859
                  - date: '2023-01-01T00:00:00.0+01:00'
                    wifree: 0
                    peak: 15128592
                    offpeak: 13567804
                  - date: '2023-01-02T00:00:00.0+01:00'
                    wifree: 0
                    peak: 11446210
                    offpeak: 10141748
                  - date: '2023-01-03T00:00:00.0+01:00'
                    wifree: 0
                    peak: 10378475
                    offpeak: 11534537
                  - date: '2023-01-04T00:00:00.0+01:00'
                    wifree: 0
                    peak: 10480913
                    offpeak: 8635229
                  - date: '2023-01-05T00:00:00.0+01:00'
                    wifree: 0
                    peak: 9363804
                    offpeak: 11496716
                peak: 658648058
                offpeak: 692375078
  internetusagereminder:
    - businessidentifier: xxxxxxxxxxx
      specurl: https://api.prd.telenet.be/omapi/public/product/627
      type: WIGOINT35
      address:
        street: xxxxxxxxxxxx
        postalcode: 'xxxx'
        municipality: xxxxxxxxxxxxxxxxx
        country: België
        housenr: 'xx'
        addressid: xxxxxxxxxxxxxxxxxxxxxxxx
      alert:
        thresholds:
          - threshold: 90
            emailreminder: true
            screenreminder: false
          - threshold: 100
            emailreminder: true
            screenreminder: false
        email:
          - xxx@telenet.be
          - xxx@telenet.be
          - xxx@telenet.be
unit_of_measurement: '%'
icon: mdi:check-network-outline
friendly_name: Telenet Telemeter
```
